export const BOOT_LINES = [
  "AMPACTOR BIOS v5.0.0",
  "Initializing compiler bootstrap...",
  "Loading DSP kernel.............. OK",
  "Mounting effect algebra......... OK",
  "Verifying L1 convergence....... OK",
  "Calibrating rollback netcode... OK",
  "Running security checks......... OK",
  "Warming up the arcade........... OK",
  "",
  "ALL SYSTEMS NOMINAL",
  "",
  "OPERATOR: MORGAN ESPITIA",
  "FOCUS: COMPILERS \u00b7 DSP \u00b7 EMBEDDED \u00b7 SECURITY",
  "STATUS: AVAILABLE FOR CONTRACT",
  "",
  "PRESS ANY KEY",
];
