export const BOOT_LINES = [
  "AMPACTOR BIOS v5.0.0",
  "Initializing compiler bootstrap...",
  "Loading DSP kernel.............. OK",
  "Mounting effect algebra......... OK",
  "Verifying L1 convergence....... OK",
  "Calibrating rollback netcode... OK",
  "Scanning security verticals.... OK",
  "Ternary inference ready........ OK",
  "",
  "ALL SYSTEMS NOMINAL",
  "",
  "OPERATOR: MORGAN ESPITIA",
  "CLEARANCE: COMPILER \u00b7 DSP \u00b7 EMBEDDED \u00b7 SECURITY",
  "STATUS: AVAILABLE FOR CONTRACT",
  "",
  "Detected: 3 INTERACTIVE PROGRAMS [INSERT COIN]",
  "",
  "PRESS ANY KEY",
];
