export const BOOT_LINES = [
  "AMPACTOR BIOS v4.2.0",
  "Initializing kernel graph...",
  "Loading DSP subsystem.......... OK",
  "Mounting effect algebra........ OK",
  "Calibrating resonance field.... OK",
  "Linking x402 payment layer..... OK",
  "Scanning 9 security verticals.. OK",
  "Phase coupling established..... OK",
  "",
  "ALL SYSTEMS NOMINAL",
  "",
  "OPERATOR: MORGAN ESPITIA",
  "CLEARANCE: FULL-STACK \u00b7 DSP \u00b7 EMBEDDED \u00b7 SOLANA",
  "STATUS: AVAILABLE FOR CONTRACT",
  "",
  "Detected: 3 CLASSIFIED PROGRAMS [ACCESS RESTRICTED]",
  "",
  "PRESS ANY KEY",
];
